version: '3.8'

services:
  server:
    build: ./server
    container_name: collatz-server
    ports:
      - "9000:9000"
    networks:
      - collatz-network

  client:
    build: ./client
    container_name: collatz-client
    environment:
      - COLLATZ_COUNT=1000
      - SERVER_HOST=server
      - SERVER_PORT=9000
    depends_on:
      - server
    networks:
      - collatz-network

networks:
  collatz-network:
    driver: bridge
